import { StyleSheet } from "react-native";

export const acbScoreStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    resizeMode: "cover",
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#222",
    textAlign: "center",
    marginBottom: 20,
  },
  meterContainer: {
    height: 25,
    width: "100%",
    backgroundColor: "#ddd",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 12,
  },
  meterBar: {
    height: "100%",
    borderRadius: 12,
  },
  scoreText: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 20,
    color: "#444",
  },
  drugItem: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  drugName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#222",
  },
  drugScore: {
    fontSize: 14,
    color: "#555",
  },
  nextButton: {
    backgroundColor: "#007BFF",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 4,
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
  },
  nextButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  header: {
  flexDirection: "row",
  alignItems: "center",
  marginBottom: 16,
  marginTop: 40,
  gap: 12,
},
});
